spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdcsystem
    #    与Docker整合时可使用以下配置（也可以使用具体的IP+端口）
    #    url: jdbc:mysql://mysql:3306/microservice_mallmanagement
    username: root
    password: 2500594037
  application:
    name: reservation-service # 指定应用名称
  main:
    allow-bean-definition-overriding: true
server:
  port: 8020 # 指定该Eureka实例的端口号
eureka:
  client:
service-url:
  defaultZone: http://localhost:8761/eureka/
#      上线测试需要使用以下配置
#      defaultZone: http://eureka-server:8761/eureka/
ORDERSERVICEURL: http://reservation-service/

## redis配置
redis:
  port: 6379
  host: localhost

logging:
  level:
    com.bdc.reservationService: debug

ignored:
  urls: #安全路径白名单
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  sign: user-su #JWT加解密使用的密钥
  expireTime: 30 #jwtToken的默认有效时间 单位分钟
  tokenHead: 'Bearer '  #JWT负载中拿到开头
