spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdcsystem
    username: root
    password: 123456
  application:
    name: admin-service # 指定应用名称
  main:
    allow-bean-definition-overriding: true
server:
  port: 8040 # 指定该Eureka实例的端口号
eureka:
  client:
service-url:
  defaultZone: http://localhost:8761/eureka/

## redis配置
redis:
  port: 6379
  host: localhost

ignored:
  urls: #安全路径白名单
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /admin/login


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  sign: admin-su #JWT加解密使用的密钥
  expireTime: 30 #jwtToken的默认有效时间 单位分钟
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  level:
    com.bdc.adminService: debug